return {
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    opts = {
      ensure_installed = {
        "bash",
        "c",
        "cmake",
        "css",
        "dockerfile",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "gpg",
        "ini",
        "json",
        "lua",
        "make",
        "markdown",
        "markdown_inline",
        "python",
        "rust",
        "sxhkdrc",
        "todotxt",
        "toml",
        "xml",
        "yaml",
        "yuck",
      },
      sync_install = true,
      highlight = {
        enabled = true,
      },
      indent = {
        enabled = true,
      },
    },
  },
}
